server:
  port: 7001

spring:
  application:
    name: provider-user-service

  redis:
    host: ${host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 10s
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  config:
    import: classpath:/config/application.yml

  cloud:
    nacos:
      discovery:
        server-addr: ${host}:${nacos.port}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:${mysql.port}/online_taxi?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ${mysql.username}
    password: ${mysql.password}

  kafka:
    bootstrap-servers: ${kafka.boot-services}
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
    listener:
      ack-mode: manual_immediate

management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露出要监控的路径

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxy.work.entities  #所有Entity别名类所在包

logging:
  level:
    root: info

# 配置 sa-token
sa-token:
  token-style: uuid
  token-name: X-Token
  is-read-cookie: false
  is-read-header: true
  is-log: true
