server:
  port: 80

spring:
  application:
    name: cloud-gateway-gateway

  redis:
    host: ${host}
    port: ${redis.port}
    password: ${redis.password}

  config:
    import: classpath:/config/application.yml

  cloud:
    nacos:
      discovery:
        server-addr: ${host}:${nacos.port}

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由

      routes:
        - id: consumer-route   #用来标识是消费者的路由
          uri: lb://consumer-feign-client #负载均衡访问消费者
          predicates:
            - Path=/taxi/**

management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露出要监控的路径
