server:
  port: 80

spring:
  application:
    name: cloud-gateway-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由

      routes:
        - id: consumer-route   #用来标识是消费者的路由
          uri: lb://consumer-feign-client #负载均衡访问消费者
          #uri: http://localhost:4001  #直接访问消费者
          predicates:
            - Path=/consumer/**

management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露出要监控的路径