server:
  port: 80

spring:
  application:
    name: cloud-gateway-gateway

  redis:
    host: ${host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 10s
    database: 0

  config:
    import: classpath:/config/application.yml

  cloud:
    loadbalancer:
      nacos:
        enabled: true

    nacos:
      discovery:
        server-addr: ${host}:${nacos.port}

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由

      routes: #映射
        - id: driver-route
          uri: lb://provider-driver-service
          predicates:
            - Path=/taxi/driver/**
          filters:
            - StripPrefix=1

        - id: order-route
          uri: lb://provider-order-service
          predicates:
            - Path=/taxi/order/**
          filters:
            - StripPrefix=1

        - id: payment-route
          uri: lb://provider-payment-service
          predicates:
            - Path=/taxi/payment/**
          filters:
            - StripPrefix=1

        - id: review-route
          uri: lb://provider-review-service
          predicates:
            - Path=/taxi/review/**
          filters:
            - StripPrefix=1

        - id: user-route
          uri: lb://provider-user-service
          predicates:
            - Path=/taxi/user/**
          filters:
            - StripPrefix=1 #去前缀/taxi
            #- AddResponseHeader=X-Response-Default-Foo, Default-Bar  #响应头添加字段

management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露出要监控的路径
