server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: update-route  #更新路由,用来更新更新时间，而不用手动更新
          uri: lb://provide-loginAndRegister
          predicates:
            - Path=/user/update/**  #断言，路径相匹配的进行路由
