server:
  port: 4001


spring:
  application:
    name: consumer-feign-client


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

  redis:
    host: localhost
    port: 6379
    #windows redis默认没有账号密码
    #username:
    #password:

feign:
  client:
    config:
      default:
        connectTimeout: 5000  #连接超时时间
        readTimeout: 5000     #读取超时时间


management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露出要监控的路径


# 配置 sa-token
sa-token:
  token-style: uuid
  token-name: X-Token
  is-read-cookie: false

  is-read-header: true




